"""Recreating migrations and adding reminder_time

Revision ID: 288ba3f00786
Revises: 
Create Date: 2025-04-02 14:35:59.768745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288ba3f00786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.Time(), nullable=True))
        batch_op.drop_column('highest_streak')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_streak', sa.INTEGER(), nullable=True))
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###
