"""activity status

Revision ID: 57c7ea876c87
Revises: 
Create Date: 2025-03-24 22:46:03.043902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c7ea876c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))
        batch_op.drop_column('last_reminded')
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('last_reminded', sa.DATETIME(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
