"""Make habit_id nullable and add ON DELETE SET NULL

Revision ID: 93dcf3f5960e
Revises: d4fa7adbf53e
Create Date: 2025-06-16 19:20:57.438674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93dcf3f5960e'
down_revision = 'd4fa7adbf53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.alter_column('habit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('user_badge_habit_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['habit_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_badge_habit_id_fkey', 'activity', ['habit_id'], ['id'])
        batch_op.alter_column('habit_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
