"""Added highest streak

Revision ID: d4fa7adbf53e
Revises: 288ba3f00786
Create Date: 2025-04-03 12:53:22.008809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fa7adbf53e'
down_revision = '288ba3f00786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('days_completed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('days_completed')
        batch_op.drop_column('highest_streak')

    # ### end Alembic commands ###
