"""Add highest streak column

Revision ID: db2a56913418
Revises: 
Create Date: 2025-03-31 20:29:42.036085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2a56913418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_streak', sa.Integer(), nullable=True))
        batch_op.drop_column('last_reminder_sent')
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('reminder_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('last_reminder_sent', sa.DATETIME(), nullable=True))
        batch_op.drop_column('highest_streak')

    # ### end Alembic commands ###
